apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss-sprava-krvi-fe-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
        pod: ss-sprava-krvi-fe-label
  template:                    
    metadata:
      labels:
        pod: ss-sprava-krvi-fe-label
    spec:
      containers:
      - name: sprava-krvi-fe-container
        image: sykoramarek/sprava-krvi-fe
        imagePullPolicy: Always

        ports:
        - name: http
          containerPort: 8080       

        resources:                  
            requests:
                memory: "32M"
                cpu: "0.1"
            limits:
                memory: "320M"
                cpu: "0.3"
                