apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss-sprava-krvi-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /ss-openapi
            - name: BASE_URL
              value: /ss-openapi-ui