apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: sykoramarek/sprava-krvi-fe
  newName: sykoramarek/sprava-krvi-fe
  newTag: 1.0.1
- name: sykoramarek/sprava-krvi-webapi
  newName: sykoramarek/sprava-krvi-webapi
  newTag: 1.0.1

replacements:
 - targets:
   - select:
         group: fe.milung.eu
         version: v1
         kind: WebComponent
         name: ss-sprava-krvi-fe
     fieldPaths:
         - spec.hash-suffix
   source:
     version: v1
     kind: Deployment
     name:  ss-sprava-krvi-fe-deployment
     fieldPath: spec.template.spec.containers.0.image
     options:
         delimiter: ':'
         index: 1
         