apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
 name: ss-gitops-repo
 namespace: wac-hospital
spec:
 interval: 1m0s
 ref:
     branch: main
 timeout: 1m0s
 url: https://github.com/Marek-FIIT/sprava-krvi-gitops
