apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

commonLabels:
  app.kubernetes.io/part-of: wac-hospital

resources:
- ../../../apps/ss-sprava-krvi-fe
- ../../../apps/ss-sprava-krvi-webapi
- ../../../apps/mongo-express

components:
- ../../../components/version-developers
- https://github.com/Marek-FIIT/sprava-krvi-webapi//deployments/kustomize/components/mongodb

patches:
- path: patches/sprava-krvi-webapi.service.yaml
